data:
  filepath:
    state: experiments/preprocessing/artifacts/preprocessor_state.json
    test: experiments/preprocessing/artifacts/titanic_test_processed.xlsx
    train: experiments/preprocessing/artifacts/titanic_train_processed.xlsx
    val: experiments/preprocessing/artifacts/titanic_val_processed.xlsx
  target_column: Survived
inference:
  decision_threshold: 0.1
model:
  activation: relu
  dropout_rate: 0.4
  hidden_dims:
  - 256
  - 128
  - 64
  input_dim: 28
  type: basic
  use_batch_norm: true
  use_residual: true
preprocessing:
  save_dir: experiments/preprocessing/artifacts
training:
  alpha: 0.25
  batch_size: 32
  epochs: 50
  gamma: 2.0
  loss_type: bce
  lr: 0.001
  min_delta: 0.0001
  optimizer_name: Adam
  patience: 5
  scheduler_type: cosine
  use_class_weights: false
  use_scheduler: false
  weight_decay: 0.0
tuning:
  dropout_range:
  - 0.3
  - 0.4
  - 0.5
  enabled: false
  hidden_dims_options:
  - - 128
  - - 256
    - 128
  - - 512
    - 256
    - 128
  lr_range:
  - 0.0001
  - 0.001
  - 0.01
