[theme]
primaryColor = "#FF4848"
backgroundColor = "#1B1F27"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"

# Optional: More customization
base = "dark"
font = "sans serif"

# Global settings
[global]
developmentMode = false

[browser]
gatherUsageStats = false
